---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-boot-generator
  name: spring-boot-generator
spec:
  selector:
    matchLabels:
      app: spring-boot-generator
  template:
    metadata:
      labels:
        app: spring-boot-generator
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SERVER_PORT
          value: '8080'
        - name: CONFIGMAP_PATH
          value: '/etc/config'
        - name: LOG_LEVEL
          value: 'info'
        image: quay.io/snowdrop/spring-boot-generator:latest
        imagePullPolicy: Always
        name: spring-boot-generator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: spring-boot-generator

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot-generator
  name: spring-boot-generator
spec:
  ports:
  - name: 8000-tcp
    port: 8000
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: spring-boot-generator

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: spring-boot-generator
spec:
  rules:
    - host: generator.snowdrop.me
      http:
        paths:
          - backend:
              serviceName: spring-boot-generator
              servicePort: 80
            path: /
  tls:
    - hosts:
      - generator.snowdrop.me
      secretName: spring-boot-generator-io-tls