apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: spring-boot-generator
    name: spring-boot-generator
  spec:
    replicas: 1
    selector:
      app: spring-boot-generator
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        labels:
          app: spring-boot-generator
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SERVER_PORT
            value: '8080'
          - name: CONFIGMAP_PATH
            value: '/etc/config'
          - name: LOG_LEVEL
            value: 'info'
          image: quay.io/snowdrop/spring-boot-generator:latest
          imagePullPolicy: Always
          name: spring-boot-generator
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
          securityContext:
            privileged: false
        volumes:
          - name: config-volume
            configMap:
              name: generator-configmap
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spring-boot-generator
        from:
          kind: ImageStreamTag
          name: spring-boot-generator:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: spring-boot-generator
    name: spring-boot-generator
  spec:
    ports:
    - name: 8000-tcp
      port: 8000
      protocol: TCP
      targetPort: 8080
    type: ClusterIP
    selector:
      app: spring-boot-generator
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: spring-boot-generator
    name: spring-boot
  spec:
    port:
      targetPort: 8000-tcp
    to:
      kind: Service
      name: spring-boot-generator
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: spring-boot-generator
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/snowdrop/spring-boot-generator:latest
      importPolicy:
        scheduled: true